// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a simplified manual implementation for development purposes

package grpc

import (
	"context"
	"google.golang.org/grpc"
)

// Empty message for requests with no parameters
type Empty struct{}

// DeviceInfo contains information about a device
type DeviceInfo struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	Os        string `json:"os"`
	OsVersion string `json:"os_version"`
	MeshIp    string `json:"mesh_ip"`
	PublicKey string `json:"public_key"`
	IsOnline  bool   `json:"is_online"`
	LastSeen  int64  `json:"last_seen"`
	SshPort   int32  `json:"ssh_port"`
	GrpcPort  int32  `json:"grpc_port"`
}

// PairingCode contains data for device pairing via QR code
type PairingCode struct {
	DeviceId   string `json:"device_id"`
	DeviceName string `json:"device_name"`
	MeshIp     string `json:"mesh_ip"`
	PublicKey  string `json:"public_key"`
	Timestamp  int64  `json:"timestamp"`
}

// HealthStatus represents the health status of the daemon
type HealthStatus struct {
	Status    string `json:"status"`
	Uptime    int64  `json:"uptime"`
	Connected bool   `json:"connected"`
	LastCheck int64  `json:"last_check"`
}

// ToolRequest represents a request to execute a named tool
type ToolRequest struct {
	ToolName string            `json:"tool_name"`
	Args     map[string]string `json:"args"`
}

// ToolResponse represents the result of executing a tool
type ToolResponse struct {
	Success bool   `json:"success"`
	Output  string `json:"output"`
	Error   string `json:"error"`
}

// DeviceServiceServer is the server API for DeviceService
type DeviceServiceServer interface {
	GetDeviceInfo(context.Context, *Empty) (*DeviceInfo, error)
	GeneratePairingCode(context.Context, *Empty) (*PairingCode, error)
	HealthCheck(context.Context, *Empty) (*HealthStatus, error)
}

// ToolServiceServer is the server API for ToolService
type ToolServiceServer interface {
	ExecuteTool(context.Context, *ToolRequest) (*ToolResponse, error)
}

// ToolServiceClient is the client API for ToolService
type ToolServiceClient interface {
	ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error)
}

type toolServiceClient struct {
	cc *grpc.ClientConn
}

// NewToolServiceClient creates a new ToolService client
func NewToolServiceClient(cc *grpc.ClientConn) ToolServiceClient {
	return &toolServiceClient{cc}
}

// ExecuteTool calls the ExecuteTool RPC
func (c *toolServiceClient) ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error) {
	out := new(ToolResponse)
	err := c.cc.Invoke(ctx, "/device.ToolService/ExecuteTool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterDeviceServiceServer registers the DeviceService server
func RegisterDeviceServiceServer(s *grpc.Server, srv DeviceServiceServer) {
	s.RegisterService(&_DeviceService_serviceDesc, srv)
}

// RegisterToolServiceServer registers the ToolService server
func RegisterToolServiceServer(s *grpc.Server, srv ToolServiceServer) {
	s.RegisterService(&_ToolService_serviceDesc, srv)
}

func _DeviceService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.DeviceService/GetDeviceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDeviceInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_GeneratePairingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GeneratePairingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.DeviceService/GeneratePairingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GeneratePairingCode(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.DeviceService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "device.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceInfo",
			Handler:    _DeviceService_GetDeviceInfo_Handler,
		},
		{
			MethodName: "GeneratePairingCode",
			Handler:    _DeviceService_GeneratePairingCode_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DeviceService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/device.proto",
}

func _ToolService_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.ToolService/ExecuteTool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ExecuteTool(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "device.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTool",
			Handler:    _ToolService_ExecuteTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/device.proto",
}
